# SPDX-FileCopyrightText: 2025-2026 Michael Serajnik <https://github.com/mserajnik>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint

on:
  push:
    branches:
      - master

jobs:
  reuse:
    name: REUSE compliance
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run reuse lint
        uses: fsfe/reuse-action@v6
